# Generated by Django 5.0.7 on 2024-08-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('person', '0005_person_current_coordinates_alter_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BD', 'Birthday'), ('WN', 'Warning'), ('IF', 'Information'), ('EM', 'Emergency'), ('OT', 'Other')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='family.family')),
            ],
        ),
    ]
