# Generated by Django 5.0.7 on 2024-08-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_familynotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familynotifications',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'Birthday'), (1, 'Warning'), (2, 'Information'), (3, 'Emergency'), (4, 'Other')]),
        ),
    ]
