# Generated by Django 5.0.7 on 2024-08-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_familyinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyinvitation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
