# Generated by Django 5.0.7 on 2024-08-02 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('status', models.IntegerField(choices=[(1, 'At Home'), (2, 'At Work'), (3, 'At School'), (4, 'In Transfer'), (5, 'In Open Place'), (6, 'In Building')], default=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family')),
            ],
        ),
        migrations.CreateModel(
            name='Kinship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinship_type', models.IntegerField(choices=[(1, 'Parent'), (2, 'Child'), (3, 'Sibling'), (4, 'Spouse'), (5, 'Grandparent'), (6, 'Grandchild'), (7, 'Aunt/Uncle'), (8, 'Nephew/Niece'), (9, 'Cousin'), (10, 'In Law'), (11, 'Friend')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinships', to='person.people')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_kinships', to='person.people')),
            ],
        ),
    ]
