# Generated by Django 5.0.7 on 2024-08-02 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family'),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
