# Generated by Django 5.0.7 on 2024-08-02 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('person', '0002_alter_people_family_alter_people_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('status', models.IntegerField(choices=[(1, 'At Home'), (2, 'At Work'), (3, 'At School'), (4, 'In Transfer'), (5, 'In Open Place'), (6, 'In Building')], default=1)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='kinship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinships', to='person.person'),
        ),
        migrations.AlterField(
            model_name='kinship',
            name='related_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_kinships', to='person.person'),
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
