# Generated by Django 5.0.7 on 2024-08-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_current_coordinates_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_family_admin',
            field=models.BooleanField(default=False),
        ),
    ]
