# Generated by Django 5.0.7 on 2024-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_is_family_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
